### ISSUE TITLE
test.sh error

### ISSUE THREAD

**Issue by redchicken75** [ICD20/step-to-hw3#1]
When I tried to use "make test", it will show an error for test.sh. Is this error related with my parser?
![image](https://user-images.githubusercontent.com/44732367/100761561-01e72e80-342e-11eb-8f25-34976a8c1361.png)

**Comment by nobodyzxc** [comment]
You may re-save the script under some windows (editor) environments, 
it made new '\r' character be added after every line in the file.

you can use dos2unix command (get it via `apt-get install -y dos2unix` under Ubuntu) to recover the script.
```
apt-get install -y dos2unix
dos2unix test/test.sh
```
